### PING-PONG
GET http://localhost:25060/
Content-Type: application/json

###

### ADD MOOD
POST http://localhost:25060/mood
Content-Type: application/json

{
    "description": "Green 3"
}

###

### PING-PONG
GET http://express-simple-api.herokuapp.com/ta-acordado?
Content-Type: application/json

###

### ADD MOOD
POST https://express-simple-api.herokuapp.com/mood
Content-Type: application/json

{
    "description": "Blue"
}

###

### GET MOODS
GET https://sea-lion-app-2hdmv.ondigitalocean.app/mood
Content-Type: application/json

###

### GET MOOD
GET http://localhost:25060/mood
Content-Type: application/json

###